import { Bidder, BidDocument, ComplianceItem, Finding } from '../../src/types/index.js';

export interface PrototypeRiskReport {
  score: number;
  level: 'LOW' | 'MEDIUM' | 'HIGH';
  factors: { factor: string; points: number; description: string }[];
  methodologyNote: string;
  disclaimer: string;
}

export class RiskAnalysisService {
  public static calculateRisk(
    _bidder: Bidder,
    documents: BidDocument[],
    complianceItems: ComplianceItem[],
    findings: Finding[]
  ): PrototypeRiskReport {
    let score = 0;
    const factors: { factor: string; points: number; description: string }[] = [];

    // Factor 1: Missing Required Documents (+20 each)
    const missingItems = complianceItems.filter(c => c.status === 'DOCUMENT_MISSING');
    if (missingItems.length > 0) {
      const points = 20 * missingItems.length;
      score += points;
      factors.push({
        factor: 'Missing Required Documents',
        points,
        description: `${missingItems.length} mandatory document(s) missing from bid submission.`,
      });
    }

    // Factor 2: Expired Documents (+20 each)
    const expiredItems = complianceItems.filter(c => c.status === 'EXPIRED');
    if (expiredItems.length > 0) {
      const points = 20 * expiredItems.length;
      score += points;
      factors.push({
        factor: 'Expired Certificates',
        points,
        description: `${expiredItems.length} uploaded certificate(s) have lapsed beyond valid evaluation date.`,
      });
    }

    // Factor 3: Entity Mismatch (+30)
    const entityMismatches = findings.filter(f => f.category === 'ENTITY_MISMATCH' || f.category === 'MII_LOCAL_CONTENT');
    if (entityMismatches.length > 0) {
      score += 30;
      factors.push({
        factor: 'Entity Name / Affiliation Discrepancy',
        points: 30,
        description: 'Discrepancy detected between bidder legal identity and document entity name (e.g. MII declaration).',
      });
    }

    // Factor 4: Address / Location Mismatches (+10)
    const addressMismatch = findings.filter(f => f.category === 'OTHER' && f.title.toLowerCase().includes('address'));
    if (addressMismatch.length > 0) {
      score += 10;
      factors.push({
        factor: 'Address Variance Across Registrations',
        points: 10,
        description: 'Operational address on GST certificate differs from factory/registered address on Udyam.',
      });
    }

    // Factor 5: Low Confidence AI Extraction (+10)
    const lowConfidenceDocs = documents.filter(d => d.confidence > 0 && d.confidence < 0.85);
    if (lowConfidenceDocs.length > 0) {
      score += 10;
      factors.push({
        factor: 'Low Document Extraction Confidence',
        points: 10,
        description: `${lowConfidenceDocs.length} document(s) scanned with optical quality/confidence below 85%.`,
      });
    }

    // Factor 6: Unresolved Verification / Independent Review Required (+10)
    const reviewReqItems = complianceItems.filter(c => c.status === 'REVIEW_REQUIRED');
    if (reviewReqItems.length > 0) {
      score += 10;
      factors.push({
        factor: 'Pending External Gateway Verification',
        points: 10,
        description: `${reviewReqItems.length} requirement(s) require manual officer verification (e.g., OEM authorization).`,
      });
    }

    // Normalize to 0-100 scale
    score = Math.min(100, score);

    let level: 'LOW' | 'MEDIUM' | 'HIGH' = 'LOW';
    if (score >= 60) {
      level = 'HIGH';
    } else if (score >= 30) {
      level = 'MEDIUM';
    }

    return {
      score,
      level,
      factors,
      methodologyNote:
        'This calculation is generated by the BidShield Prototype Risk Analysis module using deterministic rule weighting (Missing Doc: +20, Expired: +20, Entity Mismatch: +30, Low Confidence: +10, Pending Review: +10). Future production deployment incorporates Python FastAPI + XGBoost anomaly classification.',
      disclaimer:
        'Prototype Risk Analysis - Not an official GeM procurement risk score. Intended solely for officer decision support.',
    };
  }
}
